version: "3.9"

services:

  db:
    image: postgres:16-alpine

    container_name: notes-db

    restart: unless-stopped

    environment:
      POSTGRES_DB: notesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - app-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]

      interval: 10s

      timeout: 5s

      retries: 5

  backend:

    build:
      context: ./backend
      target: final

    container_name: notes-backend

    restart: unless-stopped

    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: notesdb
      DB_USER: postgres
      DB_PASSWORD: postgres

    depends_on:
      db:
        condition: service_healthy

    networks:
      - app-network

    expose:
      - "5000"

    ports:
      - "5000:5000"
  frontend:

    build:
      context: ./frontend

    container_name: notes-frontend

    restart: unless-stopped

    ports:
      - "80:80"

    depends_on:
      - backend

    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    container_name: notes-prometheus

    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

    ports:
      - "9090:9090"

    depends_on:
      - backend

    networks:
      - app-network

  grafana:
    image: grafana/grafana
    container_name: notes-grafana

    ports:
      - "3000:3000"

    depends_on:
      - prometheus

    networks:
      - app-network


volumes:
  postgres_data:

networks:
  app-network:
