global:
  scrape_interval: 5s

scrape_configs:

  - job_name: "backend"

    static_configs:
      - targets: ["notes-backend:5000"]

  - job_name: "prometheus"

    static_configs:
      - targets: ["localhost:9090"]
